### ISSUE TITLE
import monary raises OSError

### ISSUE THREAD

**Issue by s-celles** [ksuarz/monary#2] opened 2015-07-21 19:41 UTC
Hello,

I'm using Mac OS X 10.10 with Anaconda 3

I installed MongoDB

```
$ brew install mongodb --dev
```

I try my install with pymongo

```
>>> import pymongo
>>> client = pymongo.MongoClient("localhost", 27017)
>>> db = client.test
>>> db.name
u'test'
>>> db.my_collection
Collection(Database(MongoClient('localhost', 27017), u'test'), u'my_collection')
>>> db.my_collection.insert_one({"x": 10}).inserted_id
ObjectId('4aba15ebe23f6b53b0000000')
>>> db.my_collection.insert_one({"x": 8}).inserted_id
ObjectId('4aba160ee23f6b543e000000')
>>> db.my_collection.insert_one({"x": 11}).inserted_id
ObjectId('4aba160ee23f6b543e000002')
>>> db.my_collection.find_one()
{u'x': 10, u'_id': ObjectId('4aba15ebe23f6b53b0000000')}
>>> for item in db.my_collection.find():
...     print item["x"]
...
10
8
11
>>> db.my_collection.create_index("x")
u'x_1'
>>> for item in db.my_collection.find().sort("x", pymongo.ASCENDING):
...     print item["x"]
...
8
10
11
>>> [item["x"] for item in db.my_collection.find().limit(2).skip(1)]
[8, 11]
```

I was working fine

I would like to try Monary
so I also installed mongo-c-driver https://github.com/mongodb/mongo-c-driver

```
git clone https://github.com/mongodb/mongo-c-driver.git
cd mongo-c-driver
./autogen.sh
make
sudo make install
```

Then, I installed Monary

```
$ pip install monary
```

but running ipython

   $ ipython

and importing monary

   import monary

raised

```
OSError: dlopen(//anaconda/lib/python3.4/site-packages/monary/libcmonary.so, 6): Library not loaded: libcrypto.1.0.0.dylib
  Referenced from: //anaconda/lib/python3.4/site-packages/monary/libcmonary.so
  Reason: image not found
```

Any idea ?

Kind regards

**Comment by ghost** [comment] 2016-07-01 03:17
Hi,

I also face this problem, do you know how to solve?

**Comment by ajdavis** [comment] 2016-07-08 01:42
I can't reproduce this. On my Mac OS 10.10 machine, I can do:

```
$ python --version
Python 2.7.10
$ pip install numpy monary
... output ...
$ python
>>> import monary
>>> monary
<module 'monary' from '/Users/emptysquare/.virtualenvs/monary/lib/python2.7/site-packages/monary/__init__.pyc'>
```

Is your issue specific to Anaconda, or can you also reproduce it with another distribution of Python 2.7?

I'm going to close this for now, but feel free to reopen with more information.

**Closed as completed by ajdavis** 2016-07-08 01:42 UTC

**Comment by Serafim-End** [comment] 2017-03-21 17:56
Hi, I have faced with same problem, monary does not working under jupyter
when i use python2.7 it is working correctly, but not under jupyter (ipython) 


If you know the answer, please print it.
